### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-jdbc#34] opened 2015-01-08 16:38 UTC
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment] 2015-01-12 12:04
we'll find someone to do this task, soon

**Comment by dmarkov** [comment] 2015-01-16 10:14
@aoxa this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmarkov** [comment] 2015-01-16 10:15
@maurezen thank you for the ticket reported, I topped your account for 15 mins, transaction `50300869`

**Comment by dmarkov** [comment] 2015-01-28 11:20
@aoxa you're holding this ticket for 15 days already. If it's not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck)

-30 to your rating, your total score is -150

**Comment by aoxa** [comment] 2015-01-28 19:58
hi dmarkov, this issue was addressed here:
https://github.com/jcabi/jcabi-jdbc/pull/36
Please check out the points removed since you've done so for 2 tasks already solved.

**Comment by yegor256** [comment] 2015-01-28 20:03
@aoxa this ticket is still open. it's your job to make sure it gets closed, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by aoxa** [comment] 2015-01-28 20:14
@dmarkov please close this issue, it was addressed in https://github.com/jcabi/jcabi-jdbc/pull/36 . Sorry about that, will request the closing immediately for the other tasks.

**Closed** 2015-01-28 20:26 UTC
Labels: 30 mins, @aoxa, bug, DEV

**Comment by dmarkov** [comment] 2015-02-02 09:29
@aoxa thanks, paid, **30 mins** to your account, payment ID is `51004394`

+30 to your rating, your total score is -240
